 version: 2.1

 orbs:
  win: circleci/windows@2.2.0

 jobs:
   build-master:
     executor: win/default     
             
     steps:
       - checkout
       - run: dotnet build
       
 workflows:
    version: 2.0
    master_flow:
        jobs:
            - build-master:
                filters:
                    branches:
                        only: master
        
        
